### PR TITLE
pass :app_lifetime to Thread.start

### PR DESCRIPTION
**Pull request by shoichikaji**
... and test-depends HTTP::Server::Tiny

### CODE REVIEW

**Comment by tokuhirom** [comment]
hmm... test case still fail

**Comment by syohex** [comment]
NOTE: Tests with this patch are passed on my local machine with today's latest Perl6. How about re-run test ?

```
%  perl6 --version
This is perl6 version 2015.10-112-gd98dc80 built on MoarVM version 2015.10-14-g5ff3001
```

**Comment by shoichikaji** [comment]
I re-ran tests, but they failed again with the same output.
1st: https://travis-ci.org/tokuhirom/p6-WebSocket/builds/88477982
2nd: https://travis-ci.org/shoichikaji/p6-WebSocket/builds/88602307
```
t/client-server.t .. 
1..5
starting server
http server is ready: http://127.0.0.1:15555/ (pid:5016)
ready connect
ok 1 - s: ready
ok 2 - c: ready
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
I'm working on it.

**Comment by shoichikaji** [comment]
@tokuhirom thanks!

**Comment by jeturcotte** [comment]
I'm trying to install via panda on my mac; it's telling me there's both too many tests (5 out of 4) and that they start out of sequence;

Test Summary Report
-------------------
t/client-server.t (Wstat: 0 Tests: 4 Failed: 0)
  Parse errors: Tests out of sequence.  Found (2) but expected (1)
                Tests out of sequence.  Found (3) but expected (2)
                Tests out of sequence.  Found (4) but expected (3)
                Tests out of sequence.  Found (5) but expected (4)
                Bad plan.  You planned 5 tests but ran 4.
Files=6, Tests=74, 11 wallclock secs ( 0.03 usr  0.01 sys + 10.28 cusr  0.43 csys = 10.75 CPU)
Result: FAIL

This is for Websocket::P6SGI... panda said there was not 'Websocket' so I assume these are one and the same.

**Comment by syohex** [comment]
Tests are sometimes failed, sometimes passed. I suppose Perl6 Test library is not thread-safe.

**Pull request merged**
